stages:
  - deploy

deploy_lh:
  stage: deploy
  image: alpine:latest
  only:
    - main
  script:
    - apk add --no-cache lftp
    - lftp -e "
        set ftp:ssl-allow no;
        mirror -R --delete --verbose ./ /public_html/portfolio-website-api;
        bye
      " -u "$FTP_USER","$FTP_PASS" $FTP_HOST